version: 2
updates:
  # ğŸ ØªØ­Ø¯ÙŠØ« Ø­Ø²Ù… Ø¨Ø§ÙŠØ«ÙˆÙ† (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # ğŸ“¦ ØªØ­Ø¯ÙŠØ« Ø­Ø²Ù… Ø§Ù„ÙØ±ÙˆÙ†Øª Ø¥ÙŠÙ†Ø¯ (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

 